---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
work.dir <- file.path("/Users/yangzhong/Desktop/practice/double_auction")
data.dir <- file.path(work.dir, "data")
fig_zi.dir  <- file.path(work.dir, "figure")
dir.create(fig_zi.dir, showWarnings = FALSE)

source(file.path(work.dir, "code", "packages_functions.R"))
packageSetting()
```

```{r}
data.default <- read.dta13(file.path(data.dir, "simulation_output.dta"))
data.large <- read.dta13(file.path(data.dir, "simulation_output_large_1.dta"))
data.small <- read.dta13(file.path(data.dir, "simulation_output_small.dta"))

# Large vs small markets
sample.large <- read.dta13(file.path(data.dir, "market_aggregate_large.dta"))
sample.small <- read.dta13(file.path(data.dir, "market_aggregate_small.dta"))

# more large market data
data.large.2 <- read.dta13(file.path(data.dir, "simulation_output_large_2.dta"))
data.large.3 <- read.dta13(file.path(data.dir, "simulation_output_large_3.dta"))
data.large.4 <- read.dta13(file.path(data.dir, "simulation_output_large_4.dta"))
data.large.5 <- read.dta13(file.path(data.dir, "simulation_output_large_5.dta"))

# keep data of top 5 large market only
large.config <- read.dta13(file.path(data.dir, "market_large_configuration.dta"))

large.config.1 <- large.config %>%
  filter(buyer == 20, seller == 20, goods_per_trader == 3, max_value == 150, min_value == 100,
         max_cost == 109, min_cost == 50) %>%
  select(MarketID) %>%
  distinct()

large.config.2 <- large.config %>%
  filter(buyer == 30, seller == 30, goods_per_trader == 6, max_value == 150, min_value == 100,
         max_cost == 120, min_cost == 50) %>%
  select(MarketID) %>%
  distinct()

large.config.3 <- large.config %>%
  filter(buyer == 20, seller == 20, goods_per_trader == 3, max_value == 1000, min_value == 56,
         max_cost == 944, min_cost == 0) %>%
  select(MarketID) %>%
  distinct()

large.config.4 <- large.config %>%
  filter(buyer == 20, seller == 20, goods_per_trader == 3, max_value == 210, min_value == 160,
         max_cost == 149, min_cost == 90) %>%
  select(MarketID) %>%
  distinct()

large.config.5 <- large.config %>%
  filter(buyer == 50, seller == 50, goods_per_trader == 3, max_value == 150, min_value == 100,
         max_cost == 120, min_cost == 50) %>%
  select(MarketID) %>%
  distinct()

data.1 <- sample.large %>%
  right_join(large.config.1) %>%
  mutate(market = 1)

data.2 <- sample.large %>%
  right_join(large.config.2) %>%
  mutate(market = 2)

data.3 <- sample.large %>%
  right_join(large.config.3) %>%
  mutate(market = 3)

data.4 <- sample.large %>%
  right_join(large.config.4) %>%
  mutate(market = 4)

data.5 <- sample.large %>%
  right_join(large.config.5) %>%
  mutate(market = 5)

group.1 <- bind_rows(data.1, data.2, data.4) %>%
  mutate(market = as.factor(market))
```


# Figure 1
```{r}
# default
zi.default.1 <- ggplot(data.default, aes(x = trx_order_buyer, y = trx_order_seller)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  stat_density_2d(aes(fill = ..level..), geom = "polygon", alpha = 0.8, show.legend = FALSE) +
  stat_ellipse(level = 0.95, colour = my.bright.palette[5], alpha = 0.8, size = 1, linetype = "dashed") +
  scale_fill_distiller(palette = 4, direction = 1, guide = "none") +
  xlab(expression(rho[buyer])) +
  ylab(expression(rho[seller])) +
  scale_x_continuous(expand = c(0, 0), limits = c(-1.1, 1.1)) +
  scale_y_continuous(expand = c(0, 0), limits = c(-1.1, 1.1)) +
  theme(text = element_text(size = 16, family = "Helvetica"))

zi.default.2 <- ggplot(data.default, aes(x = auto_corr, y = trx_order_seller)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  stat_density_2d(aes(fill = ..level..), geom = "polygon", alpha = 0.8, show.legend = FALSE) +
  stat_ellipse(level = 0.95, colour = my.bright.palette[5], alpha = 0.8, size = 1, linetype = "dashed") +
  scale_fill_distiller(palette = 4, direction = 1, guide = "none") +
  xlab(expression(rho[price])) +
  ylab(expression(rho[seller])) +
  scale_x_continuous(expand = c(0, 0), limits = c(-1.1, 1.1)) +
  scale_y_continuous(expand = c(0, 0), limits = c(-1.1, 1.1)) +
  theme(text = element_text(size = 16, family = "Helvetica"))

zi.default.3 <- ggplot(data.default, aes(x = trx_order_buyer, y = auto_corr)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  stat_density_2d(aes(fill = ..level..), geom = "polygon", alpha = 0.8, show.legend = FALSE) +
  stat_ellipse(level = 0.95, colour = my.bright.palette[5], alpha = 0.8, size = 1, linetype = "dashed") +
  scale_fill_distiller(palette = 4, direction = 1, guide = "none") +
  xlab(expression(rho[buyer])) +
  ylab(expression(rho[price])) +
  scale_x_continuous(expand = c(0, 0), limits = c(-1.1, 1.1)) +
  scale_y_continuous(expand = c(0, 0), limits = c(-1.1, 1.1)) +
  theme(text = element_text(size = 16, family = "Helvetica"))

fig.1a <- plot_grid(zi.default.1, zi.default.2, zi.default.3, ncol = 3, align = "vh")



# small
zi.small.1 <- ggplot(data.small, aes(x = trx_order_buyer, y = trx_order_seller)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  stat_density_2d(aes(fill = ..level..), geom = "polygon", alpha = 0.8, show.legend = FALSE) +
  stat_ellipse(level = 0.95, colour = my.bright.palette[5], alpha = 0.8, size = 1, linetype = "dashed") +
  scale_fill_distiller(palette = 4, direction = 1, guide = "none") +
  xlab(expression(rho[buyer])) +
  ylab(expression(rho[seller])) +
  scale_x_continuous(expand = c(0, 0), limits = c(-1.1, 1.1)) +
  scale_y_continuous(expand = c(0, 0), limits = c(-1.1, 1.1)) +
  theme(text = element_text(size = 16, family = "Helvetica"))

zi.small.2 <- ggplot(data.small, aes(x = auto_corr, y = trx_order_seller)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  stat_density_2d(aes(fill = ..level..), geom = "polygon", alpha = 0.8, show.legend = FALSE) +
  stat_ellipse(level = 0.95, colour = my.bright.palette[5], alpha = 0.8, size = 1, linetype = "dashed") +
  scale_fill_distiller(palette = 4, direction = 1, guide = "none") +
  xlab(expression(rho[price])) +
  ylab(expression(rho[seller])) +
  scale_x_continuous(expand = c(0, 0), limits = c(-1.1, 1.1)) +
  scale_y_continuous(expand = c(0, 0), limits = c(-1.1, 1.1)) +
  theme(text = element_text(size = 16, family = "Helvetica"))

zi.small.3 <- ggplot(data.small, aes(x = trx_order_buyer, y = auto_corr)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  stat_density_2d(aes(fill = ..level..), geom = "polygon", alpha = 0.8, show.legend = FALSE) +
  stat_ellipse(level = 0.95, colour = my.bright.palette[5], alpha = 0.8, size = 1, linetype = "dashed") +
  scale_fill_distiller(palette = 4, direction = 1, guide = "none") +
  xlab(expression(rho[buyer])) +
  ylab(expression(rho[price])) +
  scale_x_continuous(expand = c(0, 0), limits = c(-1.1, 1.1)) +
  scale_y_continuous(expand = c(0, 0), limits = c(-1.1, 1.1)) +
  theme(text = element_text(size = 16, family = "Helvetica"))


fig.1b <- plot_grid(zi.small.1, zi.small.2, zi.small.3, ncol = 3, align = "vh")


# large
zi.large.1 <- ggplot(data.large, aes(x = trx_order_buyer, y = trx_order_seller)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  stat_density_2d(aes(fill = ..level..), geom = "polygon", alpha = 0.8, show.legend = FALSE) +
  stat_ellipse(level = 0.95, colour = my.bright.palette[5], alpha = 0.8, size = 1, linetype = "dashed") +
  scale_fill_distiller(palette = 4, direction = 1, guide = "none") +
  xlab(expression(rho[buyer])) +
  ylab(expression(rho[seller])) +
  scale_x_continuous(expand = c(0, 0), limits = c(-1.1, 1.1)) +
  scale_y_continuous(expand = c(0, 0), limits = c(-1.1, 1.1)) +
  theme(text = element_text(size = 16, family = "Helvetica"))

zi.large.2 <- ggplot(data.large, aes(x = auto_corr, y = trx_order_seller)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  stat_density_2d(aes(fill = ..level..), geom = "polygon", alpha = 0.8, show.legend = FALSE) +
  stat_ellipse(level = 0.95, colour = my.bright.palette[5], alpha = 0.8, size = 1, linetype = "dashed") +
  scale_fill_distiller(palette = 4, direction = 1, guide = "none") +
  xlab(expression(rho[price])) +
  ylab(expression(rho[seller])) +
  scale_x_continuous(expand = c(0, 0), limits = c(-1.1, 1.1)) +
  scale_y_continuous(expand = c(0, 0), limits = c(-1.1, 1.1)) +
  theme(text = element_text(size = 16, family = "Helvetica"))

zi.large.3 <- ggplot(data.large, aes(x = trx_order_buyer, y = auto_corr)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  stat_density_2d(aes(fill = ..level..), geom = "polygon", alpha = 0.8, show.legend = FALSE) +
  stat_ellipse(level = 0.95, colour = my.bright.palette[5], alpha = 0.8, size = 1, linetype = "dashed") +
  scale_fill_distiller(palette = 4, direction = 1, guide = "none") +
  xlab(expression(rho[buyer])) +
  ylab(expression(rho[price])) +
  scale_x_continuous(expand = c(0, 0), limits = c(-1.1, 1.1)) +
  scale_y_continuous(expand = c(0, 0), limits = c(-1.1, 1.1)) +
  theme(text = element_text(size = 16, family = "Helvetica"))


fig.1c <- plot_grid(zi.large.1, zi.large.2, zi.large.3, ncol = 3, align = "vh")


# comparison
fig.comparison <- plot_grid(fig.1a, fig.1b, fig.1c, labels = c("a", "b", "c"), label_size = 12, 
                            rel_heights = c(1, 1, 1), 
                            ncol = 1, nrow = 3, align = "vh")
ggsave(plot = fig.comparison, file.path(fig_zi.dir, "fig_1.pdf"), width = 14.4, height = 14.4)

```

# Figure 2
```{r}
plot.theory.large <- list()
plot.theory.small <- list()
for (p in 1:3) {
  plot.theory.large[[p]] <- plot.theory.comp(sample.large, p, "point", TRUE, FALSE, data.large)
  plot.theory.small[[p]] <- plot.theory.comp(sample.small, p, "point", TRUE, FALSE, data.small)
}
legend        <- get_legend(plot.theory.large[[1]] + 
                              theme(legend.justification = "center", legend.direction = "horizontal", legend.text = element_text(size = 12)))
p.merge.large <- plot_grid(plot.theory.large[[1]]+theme(legend.position="none"), 
                           plot.theory.large[[2]]+theme(legend.position="none"), 
                           plot.theory.large[[3]]+theme(legend.position="none"),
                           ncol = 3, align = "h")
p.merge.small <- plot_grid(plot.theory.small[[1]]+theme(legend.position="none"), 
                           plot.theory.small[[2]]+theme(legend.position="none"), 
                           plot.theory.small[[3]]+theme(legend.position="none"),
                           ncol = 3, align = "h")
fig.2 <- plot_grid(p.merge.small, p.merge.large, legend, labels = c("a", "b"), label_size = 12, rel_heights = c(1, 1, .1), nrow = 3)
# print(fig.si.11)
ggsave(plot = fig.2, file.path(fig_zi.dir, "fig_2.pdf"), width = 7.2, height = 4.8)

```


# Figure 3
```{r}
plot.theory.large <- list()


for (p in 1:3) {
  plot.theory.large[[p]] <- plot.theory.comp.mult(sample.large, p, "point", TRUE, FALSE, data.large, data.large.2, data.large.3, data.large.4, data.large.5)
}
legend        <- get_legend(plot.theory.large[[1]] + 
                              theme(legend.justification = "center", legend.direction = "horizontal", legend.text = element_text(size = 12)))
p.merge.large <- plot_grid(plot.theory.large[[1]]+theme(legend.position="none"), 
                           plot.theory.large[[2]]+theme(legend.position="none"), 
                           plot.theory.large[[3]]+theme(legend.position="none"),
                           ncol = 3, align = "h")

fig.large_more_comp <- plot_grid(p.merge.large, legend, rel_heights = c(1, .2), nrow = 2)
ggsave(plot = fig.large_more_comp, file.path(fig_zi.dir, "fig_large_comp.pdf"), width = 7.2, height = 2.7)

```

# Figure 4
```{r}
plot.theory.large <- list()

for (p in 1:3) {
  plot.theory.large[[p]] <- plot.theory.comp.group1(group.1, p, "point", TRUE, FALSE, data.large, data.large.2, data.large.4) + guides(colour = guide_legend(nrow = 2))
}

legend        <- get_legend(plot.theory.large[[1]] + 
                              theme(legend.justification = "center", legend.direction = "horizontal", legend.text = element_text(size = 12)))

p.merge.large <- plot_grid(plot.theory.large[[1]]+theme(legend.position="none"), 
                           plot.theory.large[[2]]+theme(legend.position="none"), 
                           plot.theory.large[[3]]+theme(legend.position="none"),
                           ncol = 3, align = "h")

fig.large_group1 <- plot_grid(p.merge.large, legend, rel_heights = c(0.7, .4), nrow = 2)
```


```{r}
plot.theory.large <- list()

for (p in 1:3) {
  plot.theory.large[[p]] <- plot.theory.group2(data.3, p, "point", TRUE, FALSE, data.large.3)
}
legend        <- get_legend(plot.theory.large[[1]] + 
                              theme(legend.justification = "center", legend.direction = "horizontal", legend.text = element_text(size = 12)))
p.merge.large <- plot_grid(plot.theory.large[[1]]+theme(legend.position="none"), 
                           plot.theory.large[[2]]+theme(legend.position="none"), 
                           plot.theory.large[[3]]+theme(legend.position="none"),
                           ncol = 3, align = "h")

fig.large_group2 <- plot_grid(p.merge.large, legend, rel_heights = c(1, .1), nrow = 2)
```


```{r}
plot.theory.large <- list()

for (p in 1:3) {
  plot.theory.large[[p]] <- plot.theory.group3(data.5, p, "point", TRUE, FALSE, data.large.5)
}
legend        <- get_legend(plot.theory.large[[1]] + 
                              theme(legend.justification = "center", legend.direction = "horizontal", legend.text = element_text(size = 12)))
p.merge.large <- plot_grid(plot.theory.large[[1]]+theme(legend.position="none"), 
                           plot.theory.large[[2]]+theme(legend.position="none"), 
                           plot.theory.large[[3]]+theme(legend.position="none"),
                           ncol = 3, align = "h")

fig.large_group3 <- plot_grid(p.merge.large, legend, rel_heights = c(1, .1), nrow = 2)
```

```{r}
fig.4 <- plot_grid(fig.large_group1, fig.large_group2, fig.large_group3,
                         labels = c("a", "b", "c"), label_size = 12, 
                         rel_heights = c(1.4, 1, 1), 
                         ncol = 1, nrow = 3, align = "vh")

ggsave(plot = fig.4, file.path(fig_zi.dir, "fig_4.pdf"), width = 7.2, height = 9)
```
